[project]
name = "src"
version = "0.0.1"
description = "An MLOps project for production grade deployment"
authors = [{name = "Gaurav Prasad", email = "gaurav.prasad.kol@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}